/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Structure;

/**
 *
 * @author ernestodecrecchio
 */
public class InfoStructurePanelView extends javax.swing.JPanel {

    public InfoStructurePanelView(Structure structure) {
        initComponents();
        
        idValueLabel.setText(structure.getId().toString());
        categoryValueLabel.setText(structure.getCategory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idValueLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        placeLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        webSiteLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        contactsLabel = new javax.swing.JLabel();
        tagLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        placeValueLabel = new javax.swing.JLabel();
        contactsValueLabel = new javax.swing.JLabel();
        categoryValueLabel = new javax.swing.JLabel();
        webSiteValueLabel = new javax.swing.JLabel();
        priceValueLabel = new javax.swing.JLabel();
        nameValueLabel = new javax.swing.JLabel();
        descriptionValueLabel = new javax.swing.JLabel();

        idLabel.setText("ID:");

        idValueLabel.setText("---");

        nameLabel.setText("Nome:");

        placeLabel.setText("Luogo:");

        categoryLabel.setText("Categoria:");

        webSiteLabel.setText("Sito Web:");

        priceLabel.setText("Prezzo Medio:");

        contactsLabel.setText("Contatti:");

        tagLabel.setText("Tag:");

        descriptionLabel.setText("Descrizione:");

        placeValueLabel.setText("---");

        contactsValueLabel.setText("---");

        categoryValueLabel.setText("---");

        webSiteValueLabel.setText("---");

        priceValueLabel.setText("---");

        nameValueLabel.setText("---");

        descriptionValueLabel.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactsLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(descriptionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(descriptionValueLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(placeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(placeValueLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idValueLabel)
                            .addComponent(nameValueLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryLabel)
                        .addGap(18, 18, 18)
                        .addComponent(categoryValueLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(webSiteLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactsValueLabel)
                            .addComponent(webSiteValueLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priceLabel)
                        .addGap(30, 30, 30)
                        .addComponent(priceValueLabel))
                    .addComponent(tagLabel))
                .addContainerGap(592, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeLabel)
                    .addComponent(placeValueLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webSiteLabel)
                    .addComponent(webSiteValueLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactsLabel)
                    .addComponent(contactsValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagLabel)
                .addContainerGap(329, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryValueLabel;
    private javax.swing.JLabel contactsLabel;
    private javax.swing.JLabel contactsValueLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel descriptionValueLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idValueLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValueLabel;
    private javax.swing.JLabel placeLabel;
    private javax.swing.JLabel placeValueLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceValueLabel;
    private javax.swing.JLabel tagLabel;
    private javax.swing.JLabel webSiteLabel;
    private javax.swing.JLabel webSiteValueLabel;
    // End of variables declaration//GEN-END:variables
}
