/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InfoStructurePanelController;
import Model.Structure;

/**
 *
 * @author ernestodecrecchio
 */
public class InfoStructurePanelView extends javax.swing.JPanel {
    
    InfoStructurePanelController controller;
    MainFrameView parent;
    Structure structure;
    
    
    public InfoStructurePanelView(MainFrameView parent, Structure structure) {
        initComponents();
        
        controller = new InfoStructurePanelController();
        this.parent = parent;
        this.structure = structure;
        
        idValueLabel.setText(structure.getId().toString());
        nameValueLabel.setText(structure.getName());
        placeValueLabel.setText(structure.getPlace());
        categoryValueLabel.setText(structure.getCategory());
        webSiteValueLabel.setText(structure.getWebSite());
        contactsValueLabel.setText(structure.getContacts());
        if(structure.getPrice() != null) {
            priceValueLabel.setText(structure.getPrice().toString());
        }
        descriptionValueTextPane.setText(structure.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idValueLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        placeLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        webSiteLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        contactsLabel = new javax.swing.JLabel();
        tagLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        placeValueLabel = new javax.swing.JLabel();
        contactsValueLabel = new javax.swing.JLabel();
        categoryValueLabel = new javax.swing.JLabel();
        webSiteValueLabel = new javax.swing.JLabel();
        priceValueLabel = new javax.swing.JLabel();
        nameValueLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionValueTextPane = new javax.swing.JTextPane();

        idLabel.setText("ID:");

        idValueLabel.setText("---");

        nameLabel.setText("Nome:");

        placeLabel.setText("Luogo:");

        categoryLabel.setText("Categoria:");

        webSiteLabel.setText("Sito Web:");

        priceLabel.setText("Prezzo Medio:");

        contactsLabel.setText("Contatti:");

        tagLabel.setText("Tag:");

        descriptionLabel.setText("Descrizione:");

        placeValueLabel.setText("---");

        contactsValueLabel.setText("---");

        categoryValueLabel.setText("---");

        webSiteValueLabel.setText("---");

        priceValueLabel.setText("---");

        nameValueLabel.setText("---");

        editButton.setText("Modifica");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        imageLabel.setText("Foto:");

        descriptionValueTextPane.setEditable(false);
        jScrollPane2.setViewportView(descriptionValueTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idValueLabel)
                                    .addComponent(nameValueLabel)))
                            .addComponent(idLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(placeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(placeValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoryLabel)
                                .addGap(18, 18, 18)
                                .addComponent(categoryValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(webSiteLabel)
                                    .addComponent(contactsLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactsValueLabel)
                                    .addComponent(webSiteValueLabel)))
                            .addComponent(tagLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceLabel)
                                .addGap(30, 30, 30)
                                .addComponent(priceValueLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageLabel)
                                    .addComponent(descriptionLabel))
                                .addGap(311, 311, 311))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idValueLabel)
                    .addComponent(descriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeLabel)
                            .addComponent(placeValueLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryLabel)
                            .addComponent(categoryValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(webSiteValueLabel)
                            .addComponent(webSiteLabel))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactsLabel)
                            .addComponent(contactsValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(priceValueLabel))
                        .addGap(34, 34, 34)
                        .addComponent(tagLabel))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(editButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        controller.setEditPanel(parent, structure);
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryValueLabel;
    private javax.swing.JLabel contactsLabel;
    private javax.swing.JLabel contactsValueLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextPane descriptionValueTextPane;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idValueLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValueLabel;
    private javax.swing.JLabel placeLabel;
    private javax.swing.JLabel placeValueLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceValueLabel;
    private javax.swing.JLabel tagLabel;
    private javax.swing.JLabel webSiteLabel;
    private javax.swing.JLabel webSiteValueLabel;
    // End of variables declaration//GEN-END:variables
}
