/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//Model
import Model.Structure;

//AWT
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author ernestodecrecchio
 */
public class MainFrameView extends javax.swing.JFrame {
  
    /**
     * Creates new form mainJFrameForm
     */
    public MainFrameView() {
        initComponents();
        this.setLayout(new BorderLayout());
        
        LogInDialogView login = new LogInDialogView(this, true);
        login.setLocationRelativeTo(null);  // *** this will center your app ***
        login.setVisible(true);
        login.setResizable(false); //Rende la finestra di login non ridimensionabile.
        if(!login.isLogged) { //se l'accesso non è stato eseguito
            dispose(); //non mostra il frame principale
        } else {
            setLocationRelativeTo(null);
            setVisible(true);
            setSummaryPanel();
            pack();
        }
    }
        
    public void setSummaryPanel() {
        SummaryPanelView a = new SummaryPanelView();
        a.setVisible(true);
        a.validate();
        validate();
        changePanel(a);
    }
    
    public void setInfoStructurePanel(Structure structure) {
        if(structure != null) {
            InfoStructurePanelView i = new InfoStructurePanelView(this, structure);
            i.setVisible(true);
            i.validate();
            validate();
            changePanel(i);
        } else {
            setSummaryPanel();
        }    
    }
    
    public void setEditStructurePanel(Structure structure) {
        if(structure != null) {
            EditStructurePanelView e = new EditStructurePanelView(this, structure);
            e.setVisible(true);
            e.validate();
            validate();
            changePanel(e);
        } else {
            setSummaryPanel();
        }    
    }
    
    public void changePanel(JPanel panel) {
        getContentPane().removeAll();
        getContentPane().add(panel); 
        getContentPane().doLayout();
        update(getGraphics());
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        summaryMenuItem = new javax.swing.JMenuItem();
        logOutMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addStructureMenuItem = new javax.swing.JMenuItem();
        searchStructureMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addUserMenuItem = new javax.swing.JMenuItem();
        searchUserMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        addReviewMenuItem = new javax.swing.JMenuItem();
        searchReviewMenuItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Generale");

        summaryMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        summaryMenuItem.setText("Riepilogo");
        summaryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(summaryMenuItem);

        logOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        logOutMenuItem.setText("Log out");
        logOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logOutMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Strutture");

        addStructureMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        addStructureMenuItem.setText("Aggiungi Struttura");
        addStructureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStructureMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(addStructureMenuItem);

        searchStructureMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        searchStructureMenuItem.setText("Ricerca Struttura");
        searchStructureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStructureMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(searchStructureMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Utenti");

        addUserMenuItem.setText("Aggiungi Utente");
        addUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(addUserMenuItem);

        searchUserMenuItem.setText("Ricerca Utente");
        searchUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(searchUserMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Recensioni");

        addReviewMenuItem.setText("Aggiungi Recensione");
        addReviewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReviewMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(addReviewMenuItem);

        searchReviewMenuItem.setText("Ricerca Recensione");
        searchReviewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchReviewMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(searchReviewMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Aiuto");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStructureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStructureMenuItemActionPerformed
        NewStructurePanelView n = new NewStructurePanelView(this);
        n.setVisible(true);
        n.validate();
        validate();
        changePanel(n);
    }//GEN-LAST:event_addStructureMenuItemActionPerformed

    private void summaryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryMenuItemActionPerformed
        setSummaryPanel();
    }//GEN-LAST:event_summaryMenuItemActionPerformed

    private void searchStructureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStructureMenuItemActionPerformed
        SearchStructurePanelView s = new SearchStructurePanelView(this);
        s.setVisible(true);
        s.validate();
        validate();
        changePanel(s);
    }//GEN-LAST:event_searchStructureMenuItemActionPerformed

    private void logOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuItemActionPerformed
        this.dispose();
        
        LogInDialogView login = new LogInDialogView(this, true);
        login.setLocationRelativeTo(null);  // *** this will center your app ***
        login.setVisible(true);
        login.setResizable(false); //Rende la finestra di login non ridimensionabile.
        if(!login.isLogged) { //se l'accesso non è stato eseguito
            dispose(); //non mostra il frame principale
        } else {
            setLocationRelativeTo(null);
            setVisible(true);
            setSummaryPanel();
            pack();
        }
    }//GEN-LAST:event_logOutMenuItemActionPerformed

    private void addUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Funzionalità non richiesta ma elemento inserito\nnel menù per possibili espansioni future", "Coming Soon" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addUserMenuItemActionPerformed

    private void searchUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Funzionalità non richiesta ma elemento inserito\nnel menù per possibili espansioni future", "Coming Soon" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_searchUserMenuItemActionPerformed

    private void addReviewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReviewMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Funzionalità non richiesta ma elemento inserito\nnel menù per possibili espansioni future", "Coming Soon" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addReviewMenuItemActionPerformed

    private void searchReviewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchReviewMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Funzionalità non richiesta ma elemento inserito\nnel menù per possibili espansioni future", "Coming Soon" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_searchReviewMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrameView().setVisible(true);
                MainFrameView frame = new MainFrameView();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addReviewMenuItem;
    private javax.swing.JMenuItem addStructureMenuItem;
    private javax.swing.JMenuItem addUserMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JMenuItem searchReviewMenuItem;
    private javax.swing.JMenuItem searchStructureMenuItem;
    private javax.swing.JMenuItem searchUserMenuItem;
    private javax.swing.JMenuItem summaryMenuItem;
    // End of variables declaration//GEN-END:variables
}
