/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.io.FileReader;
import java.io.Reader;
import java.util.Iterator;
import java.util.Set;

//Model
import Model.Structure;

//Swing
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

//AWT
import java.awt.BorderLayout;

//HTTP Java
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

//Google GSON
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import javax.swing.JPanel;

/**
 *
 * @author ernestodecrecchio
 */
public class MainFrameView extends javax.swing.JFrame {
  
    /**
     * Creates new form mainJFrameForm
     */
    public MainFrameView() {
        initComponents();
        this.setLayout(new BorderLayout());
        
        setSummaryPanel();
    }
    
    public void setSummaryPanel() {
        SummaryPanelView a = new SummaryPanelView();
        a.setVisible(true);
        a.validate();
        validate();
        changePanel(a);
    }
    
    public void setInfoStructurePanel(Structure structure) {
        if(structure != null) {
            InfoStructurePanelView i = new InfoStructurePanelView(structure);
            i.setVisible(true);
            i.validate();
            validate();
            changePanel(i);
        } else {
            setSummaryPanel();
        }    
    }
    
    public void changePanel(JPanel panel) {
        getContentPane().removeAll();
        getContentPane().add(panel); 
        getContentPane().doLayout();
        update(getGraphics());
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        summaryMenuItem = new javax.swing.JMenuItem();
        addStructureMenuItem = new javax.swing.JMenu();
        newStructureMenuItem = new javax.swing.JMenuItem();
        searchStructureMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Generale");

        summaryMenuItem.setText("Riepilogo");
        summaryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(summaryMenuItem);

        jMenuBar1.add(jMenu1);

        addStructureMenuItem.setText("Strutture");

        newStructureMenuItem.setText("Nuova Struttura");
        newStructureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStructureMenuItemActionPerformed(evt);
            }
        });
        addStructureMenuItem.add(newStructureMenuItem);

        searchStructureMenuItem.setText("Ricerca Struttura");
        searchStructureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStructureMenuItemActionPerformed(evt);
            }
        });
        addStructureMenuItem.add(searchStructureMenuItem);

        jMenuBar1.add(addStructureMenuItem);

        jMenu3.setText("Utenti");

        jMenuItem4.setText("Aggiungi Utente");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Riicerca Utente");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Recensioni");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Aiuto");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStructureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStructureMenuItemActionPerformed
        NewStructurePanelView n = new NewStructurePanelView(this);
        n.setVisible(true);
        n.validate();
        validate();
        changePanel(n);
    }//GEN-LAST:event_newStructureMenuItemActionPerformed

    private void summaryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryMenuItemActionPerformed
        setSummaryPanel();
    }//GEN-LAST:event_summaryMenuItemActionPerformed

    private void searchStructureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStructureMenuItemActionPerformed
        SearchStructurePanelView s = new SearchStructurePanelView(this);
        s.setVisible(true);
        s.validate();
        validate();
        changePanel(s);
    }//GEN-LAST:event_searchStructureMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addStructureMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem newStructureMenuItem;
    private javax.swing.JMenuItem searchStructureMenuItem;
    private javax.swing.JMenuItem summaryMenuItem;
    // End of variables declaration//GEN-END:variables
}
