/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SummaryPanelController;

//Swing
import javax.swing.table.DefaultTableModel;

//Google GSON
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;

/**
 *
 * @author ernestodecrecchio
 */
public class SummaryPanelView extends javax.swing.JPanel {

    SummaryPanelController controller;
    
    /**
     * Creates new form SummaryPanelView
     */
    public SummaryPanelView() {
        initComponents();
        
        controller = new SummaryPanelController();
        
        nOfStructuresLabel.setText(controller.getStructureNumber().toString());
        nOfReviewsLabel.setText(controller.getReviewNumber().toString());
        nOfUsersLabel.setText(controller.getUserNumber().toString());
        
        generateStructuresTable();
    }

    private void generateStructuresTable() {
        DefaultTableModel model= (DefaultTableModel) structuresTable.getModel();
        structuresTable.setModel(model);
        model.setRowCount(0);
        
        JsonArray results = controller.getInfo();
        
        for(int i = 0; i < results.size(); i++) {
            JsonObject element = results.get(i).getAsJsonObject();
                
            model.addRow(new Object[] {element.get("structureId"), element.get("name").getAsString(), element.get("averagePoints").isJsonNull() ? "---" : element.get("averagePoints") + "/5", element.get("numberOfReviews")});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nOfUsersLabel = new javax.swing.JLabel();
        nOfStructuresLabel = new javax.swing.JLabel();
        nOfReviewsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        structuresTable = new javax.swing.JTable();

        jLabel1.setText("Numero di utenti:");

        jLabel2.setText("Numero di strutture:");

        jLabel3.setText("Numero di recensioni:");

        nOfUsersLabel.setText("---");

        nOfStructuresLabel.setText("---");

        nOfReviewsLabel.setText("---");

        structuresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Punteggio Medio", "Numero Recensioni"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(structuresTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nOfStructuresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nOfReviewsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nOfUsersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nOfUsersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nOfStructuresLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nOfReviewsLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nOfReviewsLabel;
    private javax.swing.JLabel nOfStructuresLabel;
    private javax.swing.JLabel nOfUsersLabel;
    private javax.swing.JTable structuresTable;
    // End of variables declaration//GEN-END:variables
}
